# Hellow World
### Hello World

In [1]:
a=1
b=a+2
print(b)

3


In [2]:
import numpy as np

a=np.mat('1 2; 3 4')
b=np.mat('1 0; 0 1')
print(a)
print(b)
print(a*b)

[[1 2]
 [3 4]]
[[1 0]
 [0 1]]
[[1 2]
 [3 4]]


In [3]:
c=np.array([[1, 2], [3, 4]])
d=np.array([[1, 0], [0, 1]])
print(c)
print(d)
print(c*d)

[[1 2]
 [3 4]]
[[1 0]
 [0 1]]
[[1 0]
 [0 4]]


In [4]:
print(np.dot(c,d))  # similar to matrix multiplication

[[1 2]
 [3 4]]


In [5]:
print(a**2)

[[ 7 10]
 [15 22]]


In [6]:
print(c**2)

[[ 1  4]
 [ 9 16]]
