# Matrix 
# copy: ctrl-c,   paste: ctrl-v,   cut: ctrl-x 

In [1]:
import numpy as np

A1 = np.matrix('1 2; 3 4')
print(A1)

[[1 2]
 [3 4]]


In [2]:
B1 = np.matrix('3 0 -1; 1 -1 2')
print(B1)

[[ 3  0 -1]
 [ 1 -1  2]]


In [3]:
C1 = A1*B1
print(C1)

[[ 5 -2  3]
 [13 -4  5]]


In [4]:
A2 = np.matrix('1 2; 3 4')
print(A2)
B2 = np.matrix('3 0; 1 -1')
print(B2)
C2 = A2*B2
print(C2)

[[1 2]
 [3 4]]
[[ 3  0]
 [ 1 -1]]
[[ 5 -2]
 [13 -4]]


In [5]:
D2 = B2*A2
print(D2)

[[ 3  6]
 [-2 -2]]


In [6]:
Dinv = np.linalg.inv(D2)
print(Dinv)

[[-0.33333333 -1.        ]
 [ 0.33333333  0.5       ]]


In [7]:
X3 = np.matrix('2; -1; 3')
A3 = np.matrix('2 1 -1; 1 -2 1; -1 2 3')
B3 = A3*X3
print('A3=',A3)
print('X3=',X3)
print('B3=',B3)
A3inv = np.linalg.inv(A3)
print('A3inv=',A3inv)
X4 = A3inv*B3
print('X4=',X4)


A3= [[ 2  1 -1]
 [ 1 -2  1]
 [-1  2  3]]
X3= [[ 2]
 [-1]
 [ 3]]
B3= [[0]
 [7]
 [5]]
A3inv= [[ 0.4   0.25  0.05]
 [ 0.2  -0.25  0.15]
 [ 0.    0.25  0.25]]
X4= [[ 2.]
 [-1.]
 [ 3.]]
